title: Hacked Jekyll
description: Jekyll microtheme that looks like JSON
baseurl: ""
url: https://cmsthomson.github.io

remote_theme: hacked-jekyll

quotes: values
lowercase: keys

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never

# Color scheme (One Dark Pro-inspired)
color_bg: gray-10
color_text: gray-0
color_punct: gray-5
color_key: blue-4
color_value: cyan-4
color_hover: blue-6
